feat - show different warning message based on billing type
APISuite/apisuite-billing-extension-ui pull request #47
Opened 2022-01-06 07:26 UTC by JanssenBrm

When a user selects to do a payment through a top-up or start/change a subscription, they get a confirmation dialog before being redirected to payment gateway. One important component of this dialog is the warning message to direct the user to the terms and conditions. However, this warning message is common for all billing methods. In the case of a top-up, the warning shows information about the subscriptions:

![image](https://user-images.githubusercontent.com/10883374/148344705-5531b870-f768-418f-9d6d-08941262a78f.png)

The feature proposed in this pull request is to make the text depending on the billing method. This would allow administrators of the marketplace to set a different warning text for top-ups and subscriptions. Furthermore, if a warning message is not required for one of the methods (for example topups), the text can be hidden through the translations.

2022-01-11 14:37 UTC, a31859 requested changes
Build files should not be in the PR.

2022-01-11 14:37 UTC, a31859 commented on lib/translations/en-US.json
> +          "text": "Dit is een test voor popups"
Make this an empty string or give proper translations so it will not show this text when no translation is added in the backend.

2022-01-12 11:54 UTC, JanssenBrm commented on lib/translations/en-US.json
> +          "text": "Dit is een test voor popups"
My apologies, forgot to update the translations. Will fix asap!

2022-01-12 17:29 UTC, a31859 approved these changes

2022-01-12 17:29 UTC, merged

2022-01-13 12:39 UTC, apisuite-machine-user commented
:tada: This PR is included in version 1.10.2 :tada:

The release is available on [GitHub release](https://github.com/APISuite/apisuite-billing-extension-ui/releases/tag/v1.10.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: