(APXB-14) - FE: Fetch user information from API
APISuite/apisuite-billing-extension-ui pull request #6
Opened 2021-05-04 11:16 UTC by pedroCloudoki

Added ability to retrieve user details (credits and subscriptions).

2021-05-04 13:12 UTC, s1moe2 requested changes

2021-05-04 13:12 UTC, s1moe2 commented on src/pages/Billing/sagas.ts
> +    const getAllUserDetailsActionUrl = `https://billing.develop.apisuite.io/users/${action.userID}`
@pedroCloudoki this can't be hardcoded

2021-05-04 17:18 UTC, mstrk approved these changes

2021-05-07 07:20 UTC, s1moe2 approved these changes

2021-05-07 07:30 UTC, merged